//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("TakeADrink")]
[assembly: System.Reflection.AssemblyDescription("Description")]
[assembly: System.Reflection.AssemblyProduct("Productname")]
[assembly: System.Reflection.AssemblyCopyright("Copyright")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("2017.5.27.10.37.b4066ac")]
[assembly: System.Reflection.AssemblyVersion("2017.5.27.*")]
[assembly: System.Reflection.AssemblyFileVersion("2017.5.27.*")]


